spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hogwarts}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true